typography_spectrum: 0.8286479676607996
color:
  brandStrength: 0.6806544556748122
  lightness: 0.32590842223726213
  saturation: 0.11408621538430452
  rhythmicContrast: 0.856641486287117
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.846789772156626
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7fbd0ed-8a74-4481-b261-8676a5dfb165.png
name: NRC Photography
navigation: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe1b07ea-c6f3-41e8-957e-61c33ed1aa9c.png
title: The Path of Light and Shadows
description: NRC Photography
